"""initial schema

Revision ID: 24b6c72a72a6
Revises: 2c786f6fcf5b
Create Date: 2026-07-26 20:22:22.832737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '24b6c72a72a6'
down_revision: Union[str, None] = '2c786f6fcf5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
